### ISSUE TITLE
Edamame does not launch on Drauger OS 7.7 due to Python version conflict

### ISSUE THREAD

**Issue by Batcastle** [drauger-os-development/edamame#105]
On Drauger OS 7.7, Edamame refuses to launch due to a Python version conflict.

Edamame compiles for Python 3.11 on Drauger OS 7.7, however, in `python3-parted`, one the submodules (`_ped`) is compiled for Python 3.12. As such, it is not loaded when running Python 3.11, like Edamame is.

Possible solutions:
 - Compile Edamame for Python 3.12
   - Depends on Nuitka support
   - Python 3.12 is not available in Ubuntu 20.04 or Drauger OS 7.6. It will need to be backported if this route is used.
   - This will likely be a recurring issue if this route is used.
 - Build in some redundancy, so if Edamame fails to launch with the _preferred_ Python version, it can re-launch itself with the available Python version
   - This would require quite a bit of engineering, as source code versions of all compiled scripts will need to be available, but not in the way
   - `usr/bin/edamame.cxx` would need to catch this failure, detect it and infer it from the log file at `/tmp/edamame.log`, and auto-relaunch as needed.
   - This will need to be indicated in log files so that developers know what is happening (this part is a trivial matter).
 - Stop compiling Edamame
   - This would be the simplest option.
   - This would negate any possible performance boost from compilation.
   - Would reduce package build time.

**Comment by SenlisO** [comment]
This issue is fixed by pull request #104 waiting to be approved.

**Comment by Batcastle** [comment]
Fixed by #107
